use avl::AVLTreeStructure;
use common::Dotfile;

fn main() {
    let mut avl = AVLTreeStructure::new();
    avl.insert(1);
    avl.insert(2);
    avl.insert(3);
    avl.insert(4);
    avl.insert(5);
    avl.insert(6);
    avl.insert(7);
    avl.insert(8);
    avl.insert(9);
    avl.insert(10);
    avl.insert(11);
    avl.insert(12);
    avl.insert(13);
    println!("Searching 10");
    println!("{:#?}",avl.find_by_key(10));
    println!("Searching 0");
    println!("{:#?}",avl.find_by_key(0));
    println!("{:#?}", avl);
    let mut dot_file = Dotfile::new("./avl.dot");
    avl.draw_tree(&mut dot_file);
    dot_file.write_file();
    // avl.delete(6);
    //avl.delete(25);
    println!("After delete");
    let mut dot_file = Dotfile::new("./avl_after_delete.dot");
    avl.draw_tree(&mut dot_file);
    dot_file.write_file();
    println!("{:#?}", avl);
    let number_of_leaves = AVLTreeStructure::number_of_leaves(&avl.root);
    let mut height_of_tree = AVLTreeStructure::height_of_tree(&avl.root);
    println!("Number of leaves:{}",number_of_leaves);
    println!("Height of Tree:{}",height_of_tree);
    AVLTreeStructure::in_order_traversal(&avl.root);
    println!("Is tree empty: {}",avl.tree_is_empty());
}
